complete final
samatov-rsk/Task31 pull request #1
Opened 2023-09-22 12:34 UTC by samatov-rsk

2023-09-24 13:44 UTC, sokramento requested changes

2023-09-24 13:44 UTC, sokramento commented on src/main/java/com/samatov/springCourse/controller/UserController.java
> +    @Autowired()
@Autowired можно без скобок

2023-09-24 13:44 UTC, sokramento commented on src/main/java/com/samatov/springCourse/controller/UserController.java
> +    @GetMapping()
можно без скобок, если ничего нет внутри

2023-09-24 13:44 UTC, sokramento commented on src/main/java/com/samatov/springCourse/controller/UserController.java
> +        List userList = userService.getAllUsers();
бесполезная переменная, вызови сразу метод в 32 строчке

2023-09-24 13:44 UTC, sokramento commented on src/main/java/com/samatov/springCourse/controller/UserController.java
> +    @PostMapping()
скобки

2023-09-24 13:44 UTC, sokramento commented on src/main/java/com/samatov/springCourse/controller/UserController.java
> +    public String getUser(@PathVariable("id") int id, Model model) {
int userId

2023-09-24 13:44 UTC, sokramento commented on src/main/java/com/samatov/springCourse/controller/UserController.java
> +    public String edit(Model model, @PathVariable("id") int id) {
int userId понятнее, потому что в проекте может быть несколько сущностей и у кажого свой id

2023-09-24 13:44 UTC, sokramento commented on src/main/java/com/samatov/springCourse/controller/UserController.java
> +    public String update(@ModelAttribute("user") User user, @PathVariable("id") int id) {
userId

2023-09-24 13:44 UTC, sokramento commented on src/main/java/com/samatov/springCourse/controller/UserController.java
> +    public String delete(@PathVariable("id") int id) {
userId

2023-09-24 13:44 UTC, sokramento commented on src/main/java/com/samatov/springCourse/dao/UserDaoImpl.java
> +@Transactional
лучше над классом не вешать, а вешать над методами отдельно, потому что могут быть в сервисе методы, которые могут  не использовать транзакционность

2023-09-24 13:44 UTC, sokramento commented on src/main/java/com/samatov/springCourse/dao/UserDAO.java
> +    List<User>getAllUsers ();
отступы между методами поставь как в сервисе

2023-09-24 13:44 UTC, sokramento commented on src/main/java/com/samatov/springCourse/service/UserServiceImpl.java
> +@Transactional
и тут тоже @Transactional?

2023-09-24 13:44 UTC, sokramento commented on src/main/java/com/samatov/springCourse/service/UserServiceImpl.java
> +@Transactional
в дао можно убрать, а тут проставить над методами

2023-09-24 15:14 UTC, samatov-rsk commented on src/main/java/com/samatov/springCourse/controller/UserController.java
> +    @Autowired()
fix

2023-09-24 15:14 UTC, samatov-rsk commented on src/main/java/com/samatov/springCourse/controller/UserController.java
> +    @GetMapping()
fix

2023-09-24 15:15 UTC, samatov-rsk commented on src/main/java/com/samatov/springCourse/controller/UserController.java
> +        List userList = userService.getAllUsers();
fix

2023-09-24 15:15 UTC, samatov-rsk commented on src/main/java/com/samatov/springCourse/controller/UserController.java
> +    @PostMapping()
fix

2023-09-24 15:16 UTC, samatov-rsk commented on src/main/java/com/samatov/springCourse/controller/UserController.java
> +    public String getUser(@PathVariable("id") int id, Model model) {
исправить int на Integer

2023-09-24 15:17 UTC, samatov-rsk commented on src/main/java/com/samatov/springCourse/controller/UserController.java
> +    public String update(@ModelAttribute("user") User user, @PathVariable("id") int id) {
fix

2023-09-24 15:17 UTC, samatov-rsk commented on src/main/java/com/samatov/springCourse/controller/UserController.java
> +    public String delete(@PathVariable("id") int id) {
fix

2023-09-24 15:17 UTC, samatov-rsk commented on src/main/java/com/samatov/springCourse/dao/UserDaoImpl.java
> +@Transactional
fix

2023-09-24 15:17 UTC, samatov-rsk commented on src/main/java/com/samatov/springCourse/dao/UserDAO.java
> +    List<User>getAllUsers ();
fix

2023-09-24 15:18 UTC, samatov-rsk commented on src/main/java/com/samatov/springCourse/service/UserServiceImpl.java
> +@Transactional
fixed

2023-09-24 15:25 UTC, samatov-rsk commented on src/main/java/com/samatov/springCourse/service/UserServiceImpl.java
> +@Transactional
fixed Transactional(readOnly=true)

2023-09-24 15:27 UTC, samatov-rsk commented on src/main/java/com/samatov/springCourse/controller/UserController.java
> +    public String getUser(@PathVariable("id") int id, Model model) {
fixed int changed to Integer

2023-09-26 12:14 UTC, samatov-rsk commented on src/main/java/com/samatov/springCourse/controller/UserController.java
> +    public String getUser(@PathVariable("id") int userId, Model model) {
fixed

2023-09-26 12:16 UTC, samatov-rsk commented on src/main/java/com/samatov/springCourse/dao/UserDaoImpl.java
> +        return entityManager.find(User.class, userId);
fixed

2023-09-26 13:36 UTC, sokramento commented on docker-compose.yaml
> +  my-db:
получилось поднять приложение с фронтом и протестить полностью?

2023-09-26 13:38 UTC, sokramento commented on src/main/java/com/samatov/springCourse/controller/UserController.java
> +    public String newPerson(@ModelAttribute("user") User user) {
этот метод возвращает страничку ? 

getNewUserPage() тогда метод лучше назвать

2023-09-26 13:42 UTC, sokramento commented on src/main/java/com/samatov/springCourse/dao/UserDAO.java
> +}
добавь 19 строку и пусть она будет пустая, вот [почему](https://stackoverflow.com/questions/2287967/why-is-it-recommended-to-have-empty-line-in-the-end-of-a-source-file)

2023-09-26 13:42 UTC, sokramento commented on src/main/java/com/samatov/springCourse/dao/UserDAO.java
> +}
сделай так везде , во всех  файлах

2023-09-26 13:45 UTC, sokramento commented on src/main/java/com/samatov/springCourse/model/User.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
статик импорт

2023-09-26 13:46 UTC, sokramento commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:mysql://localhost:3306/db_users
вот эти все значения у каждой проперти в реальных проектах обычно лежат в конфиг серверах, это так на зметку

зарезолви этот коммент потом

2023-09-26 13:46 UTC, sokramento commented on src/main/resources/application.properties
> +server.port=8090
вот эти все значения у каждой проперти в реальных проектах обычно лежат в конфиг серверах, это так на зметку

зарезолви этот коммент потом

2023-09-26 14:38 UTC, samatov-rsk commented on docker-compose.yaml
> +  my-db:
yes.

2023-09-26 14:38 UTC, samatov-rsk commented on src/main/java/com/samatov/springCourse/controller/UserController.java
> +    public String newPerson(@ModelAttribute("user") User user) {
fixed

2023-09-26 14:40 UTC, samatov-rsk commented on src/main/java/com/samatov/springCourse/dao/UserDAO.java
> +}
fixed

2023-09-26 14:40 UTC, samatov-rsk commented on src/main/java/com/samatov/springCourse/model/User.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
fixed

2023-09-27 12:21 UTC, owner1996 approved these changes

2023-09-28 11:21 UTC, sokramento commented on src/main/java/com/samatov/springCourse/dao/UserDAO.java
> +}
не вижу чтобы строку добавил, плюс есть файлы и классы где этих строк тоже нет, выше скинул ссылку еще

2023-09-28 11:21 UTC, sokramento commented on src/main/java/com/samatov/springCourse/dao/UserDaoImpl.java
> +}
вот! 49 строчку добавь

2023-09-28 11:22 UTC, sokramento commented on src/main/java/com/samatov/springCourse/dao/UserDAO.java
> +}
ты сам пройдись по всем классам, я же не буду оставлять везде комменты по этому вопросу

2023-09-28 11:37 UTC, samatov-rsk commented on src/main/java/com/samatov/springCourse/dao/UserDAO.java
> +}
fixed

2023-09-28 11:51 UTC, samatovM approved these changes

2023-09-28 11:52 UTC, sokramento approved these changes

2023-09-28 12:01 UTC, merged